import Foundation

// Bundle.module is auto-generated by Swift Package Manager.
// This extension provides the same accessor for CocoaPods builds.
#if !SWIFT_PACKAGE
extension Bundle {
    static var module: Bundle {
        let bundleName = "Deviice"
        let candidates: [URL?] = [
            Bundle.main.resourceURL,
            Bundle(for: BundleToken.self).resourceURL,
            Bundle.main.bundleURL,
        ]
        for candidate in candidates {
            if let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle"),
               let bundle = Bundle(url: bundlePath) {
                return bundle
            }
        }
        return Bundle(for: BundleToken.self)
    }
}

private final class BundleToken {}
#endif
